export const ALERTS = {
  INVALID_EMAIL: 'alert_invalid_email',
  EMAIL_IN_USE: 'alert_email_in_use',
  PASSWORD_LENGTH: 'alert_password_length',
  REQUIRED: 'alert_required',
  INVALID_DATA: 'alert_invalid_data',
  SERVER_ERROR: 'alert_server_error',
  NOT_FOUND: 'alert_not_found',
  INVALID_PASSWORD: 'Nieprawidłowe hasło',
  INVALID_CREDENTIALS: 'alert_invalid_credentials',
  AUTHENTICATION_ERROR: 'alert_authentication_error',
  INVALID_TOKEN: 'alert_invalid_token',
  TOKEN_NOT_FOUND: 'alert_token_not_found',
  TOKEN_PROVIDED: 'alert_token_provided',
  FORBIDDEN: 'alert_forbidden',
  TOKEN_EXPIRED: 'alert_token_expired',
  USER_NOT_FOUND: 'alert_user_not_found',
  INTERNAL_SERVER_ERROR: 'Błąd serwera spróbuj ponownie później',
  EMAIL_ALREADY_EXISTS: 'alert_email_already_exists',
  USER_BLOCKED_SUCCESFULLY: 'alert_user_blocked_succesfully',
  USER_UNBLOCKED_SUCCESFULLY: 'alert_user_unblocked_succesfully',
  CURRENT_PASSWORD_INCORRECT: 'Stare hasło jest nieprawidłowe',
  PASSWORD_UPDATED_SUCCESSFULLY: 'Zmiana hasła przebiegła pomyślnie',
  USER_IS_BLOCKED: 'Użytkownik został zablokowany',
  USER_IS_UNBLOCKED: 'Użytkownik został zablokowany',
  USER_ALREADY_EXISTS: 'Użytkownik o podanym adresie email już istnieje',
  USER_REGISTERED_SUCCESSFULLY: 'Użytkownik pomyślnie zarejestrowny',
  EVENT_NOT_FOUND: 'Nie znaleziono wydarzenia',
  MISSING_REQUIRED_FIELDS: 'Uzupełnij brakujące dane',
  INVALID_GOOGLE_TOKEN: 'Nieprawidłowy token google',
};
